export { perfumes as perfumesTable } from "./perfumes";
export { users as usersTable } from "./users";
export { companies as companiesTable } from "./companies";
export { shops as shopsTable } from "./shops";
export { shopStaff as shopsStaffTable } from "./shopStaff";
export { alcohols as alcoholsTable } from "./alcohols";
export { alcoholLots } from "./alcoholLots";
export { perfumesCompounds as perfumesCompoundsTable } from "./perfumesCompounds";
export { bottles as bottlesTable } from "./bottles";
export { aging as agingTable } from "./agings";
export { addresses as addressesTable } from "./addresses";
export { amountTiersTable } from "./amountTiers";
export { compoundLotsTable } from "./compoundLots";
